plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
