name: build-whl
on:
  workflow_call:
    inputs:
      build-label:
        description: "requested runner label"
        type: string
        required: true
      dev:
        type: boolean
        required: true 
      release:
        type: boolean
        required: true
      name:
        type: string
      internal:
        type: boolean
      filename:
        type: string
        required: true
      

jobs:
  build:
    runs-on: ${{ inputs.build-label }}
    outputs:
      wheel: ${{ steps.push-wheel.outputs.wheel }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to s3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
        aws-region: us-east-1 

    - name: Build PyPi Wheel
      id: build-wheel
      uses: neuralmagic/nm-actions/actions/pypi_build@main
      with:
        dev: ${{ inputs.dev }}
        release: ${{ inputs.release }}
        name: ${{ inputs.name }}
    
    - name: Push to s3 bucket
      id: push-wheel
      uses: neuralmagic/nm-actions/actions/s3_push@main
      with:
        filename: ${{ inputs.filename }}
        internal: ${{ inputs.internal }}
    
