name: Run nightly docker container
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build-container:
    name: Push Version Tagged Nightly Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          context: ./docker_nightly
          push: false