name: build-whl
on:
  workflow_call:
    inputs:
      build-label:
        description: "requested runner label"
        type: string
        required: true
      whl:
        type: string

jobs:
    pull-wheel-and-test:
      needs: build-wheel-and-push
      runs-on: ${{ inputs.build-label }}
      steps:
      - name: Login to s3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
          aws-region: us-east-1 

      - name: Make directory for wheel
        run: |
            mkdir dist_s3

      - name: Pull from s3
        uses: neuralmagic/nm-actions/actions/s3_pull@main
        with:
          filename: ${{ inputs.whl }}
          dst: dist_s3

      - name: Install Wheel
        run: |
            echo "FILENAME=$(echo dist_s3/*.whl)" >> $GITHUB_ENV
            echo $FILENAME

      - name: Install 
        run: |
            pip install $FILENAME[dev]
            pip list

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove non-test files and run tests
        run: |
              rm -rf src
              make test