name: Upload Data Tar

on:
  push:
    branches: ["include-data-files"]
    paths:
      - 'src/sparseml/yolov5/models'
      - 'src/sparseml/yolov5/models_v5.0'
      - 'src/sparseml/yolov5/data'

jobs:
  build-tar:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git branch --show-current
      - name: get tag
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo v${GITHUB_REF_NAME#*/})"
      - name: build tar
        run: cd src/sparseml && find yolov5 -name "*.yaml" -o -name "*.sh" | tar -czvf data.tar.gz -T -
        id: build_tar
      - name: Upload Data Asset
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/sparseml/data.tar.gz
          asset_name: data.tar.gz
          tag: v0.12
          overwrite: true
