name: Upload Data Tar

on:
  push:
    branches:
      - "master"

jobs:
  build-wheel:
    runs-on: "ubuntu-latest"
    steps:
        uses: actions/checkout@v2
      - name: "Checking if yolov5 data was changed"
        id: yolov5-check
        run: >
          ((git diff --name-only origin/main HEAD | grep -E "src/sparseml/yolov5/[data|models]")
          || (echo $GITHUB_REF | grep -E "refs/heads/[release/|main]"))
          && echo "::set-output name=output::yolov5" || echo "::set-output name=output::"
      - name: build tar
        if: ${{ steps.yolov5-check.outputs.yolov5 }}
        run: cd src/sparseml && find yolov5 -name "*.yaml" -o -name "*.sh" | tar -cf data.tar.gz -T -
        id: build_tar
      - name: Upload Data Asset
      if: ${{ steps.yolov5-check.outputs.yolov5 }}
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: neuralmagic/yolov5
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: data.tar.gz
          asset_name: data.tar.gz
          tag: "data"
          overwrite: true
